services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "${LANGFUSE_PORT:-3000}:3000"
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/postgres
      - DATABASE_HOST=langfuse-db
      - DATABASE_USER=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=${LANGFUSE_DATABASE_PASSWORD:-postgres}
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      # - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

    networks:
      - langindex-net

  langfuse-db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${LANGFUSE_DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - langindex-net

volumes:
  database_data:
    driver: local

networks:
  langindex-net:
