services:
  phoenix:
    image: arizephoenix/phoenix:latest
    depends_on:
      - phoenix-db
    ports:
      - 6006:6006
      - 4317:4317
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:${PHOENIX_POSTGRES_PASSWORD:-1122334455}@db:5432/postgres
  
  phoenix-db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PHOENIX_POSTGRES_PASSWORD:-1122334455}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - langindex-net

volumes:
  database_data:
    driver: local