include:
  - ../langfuse-compose.yml

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LANGFUSE_URL=http://langfuse:3000
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: /Users/Oleh_Hrynets/Library/CloudStorage/OneDrive-EPAM/Data_Archive
        target: /mnt/docs
    command: sleep infinity
    networks:
      - langindex-net

networks:
  langindex-net:

volumes:
  database_data:
    driver: local